offset_dir: /tmp
outputs:
  console: file+json:///dev/stdout
  statsd: udp+statsd://localhost:2003
groups:
  syslog:
    glob: /var/log/system.log
    pattern: (?P<date>.*?:[0-9]+) (?P<user>\S+) (?P<prog>\w+)\[(?P<pid>\d+)\]: (?P<text>.*)
    fields:
      timestamp:
        name: date
        type: date
        format: Jan _2 15:04:05
      line: 
        group: 0
      text: 
        type: string
      tokens:
        name: text
        type: tokenized
        pattern: \S+\b
      pid:
        type: gauge